[package]
name = "convolution_mp"
version = "0.1.0"
edition = "2021"

[dependencies]
gnuplot = "0.0.37"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
